INSERT INTO exercise (name, primary_muscle_group, secondary_muscle_group, push_or_pull)
VALUES
('Bench_BB_Decline', 'Chest', 'Triceps', 'push'),
('Bench_DB_Decline', 'Chest', 'Triceps', 'push'),
('Bench_BB_Flat', 'Chest', 'Triceps', 'push'),
('Bench_DB_Flat', 'Chest', 'Triceps', 'push'),
('Bench_BB_Incline', 'Chest', 'Triceps', 'push'),
('Bench_DB_Incline', 'Chest', 'Triceps', 'push'),
('Fly_Decline', 'Chest', 'Triceps', 'push'),
('Fly_Flat', 'Chest', 'Triceps', 'push'),
('Fly_Incline', 'Chest', 'Triceps', 'push'),
('Dips', 'Chest', 'Triceps', 'push'),
('Push_Up', 'Chest', 'Triceps', 'push'),
('Pull_Up', 'Back', 'Biceps', 'pull'),
('Sit_Up', 'Abs', 'Full', 'pull'),
('Row_LM', 'Back', 'Biceps', 'pull'),
('Row_1Arm', 'Back', 'Biceps', 'pull'),
('Pullover', 'Back', 'Biceps', 'pull'),
('Squat_Landmine', 'Legs', 'Quads', 'push'),
('Squat_Barbell', 'Legs', 'Quads', 'push'),
('Lunge_DB', 'Legs', 'Quads', 'push'),
('Hip_Thrust', 'Legs', 'Glutes', 'push'),
('Leg_Curl', 'Legs', 'Hamstrings', 'pull'),
('Leg_Extension', 'Legs', 'Quads', 'push'),
('Press_BB_Shoulder', 'Shoulders', 'Triceps', 'push'),
('Press_DB_Shoulder', 'Shoulders', 'Triceps', 'push'),
('Curl_Incline', 'Biceps', 'Forearm', 'pull'),
('Curl_DB', 'Biceps', 'Forearm', 'pull'),
('Curl_EZ', 'Biceps', 'Forearm', 'pull'),
('Curl_Hammer', 'Biceps', 'Forearm', 'pull'),
('Curl_Spider', 'Biceps', 'Forearm', 'pull'),
('Curl_Preacher', 'Biceps', 'Forearm', 'pull'),
('Lateral Raise', 'Shoulders', 'Delts', 'push'),
('Upright Row', 'Back', 'Traps', 'pull'),
('Fly_Delt', 'Shoulders', 'Delts', 'push'),
('Side_Bend', 'Abs', 'Obliques', 'push'),
('Deadlift_Romanian', 'Back', 'Glutes', 'pull'),
('Bench_BB_CloseGrip', 'Triceps', 'Chest', 'push'),
('Curl_Reverse', 'Biceps', 'Forearm', 'pull'),
('Step_Ups', 'Legs', 'Quads', 'push');

SELECT * FROM exercise;